import { motion } from 'framer-motion';
import { BookOpen, Lightbulb, ListChecks } from 'lucide-react';

export default function HelpPageEnhanced() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 6 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35 }}
      className="space-y-6"
    >
      <div className="rounded-[28px] border border-border bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(255,255,243,0.94))] p-7 shadow-[0_30px_70px_-46px_rgba(84,134,135,0.95)]">
        <p className="text-xs uppercase tracking-[0.24em] text-primary/80">Help and About</p>
        <h2 className="mt-2 text-2xl font-medium text-foreground">How to read and use the tool</h2>
        <p className="mt-2 text-[15px] leading-7 text-muted-foreground">
          This page collects the essential theory and input rules so students can move from definition to practice without leaving the app.
        </p>
      </div>

      <div className="mx-auto max-w-4xl space-y-6">
        <Section title="What is a Context-Free Grammar?" icon={<BookOpen className="h-4 w-4" />}>
          <p>
            A context-free grammar (CFG) is a formal system used to describe the syntax of programming languages,
            natural language subsets, and other structured formats. It consists of production rules that define how
            strings in a language can be generated by repeatedly replacing non-terminal symbols.
          </p>
          <p className="mt-3">
            CFGs are central to compiler design because they help us describe nested structure, operator precedence,
            and valid sentence formation in a way that can be visualized through derivations and parse trees.
          </p>
        </Section>

        <Section title="Grammar Input Format" icon={<ListChecks className="h-4 w-4" />}>
          <p className="mb-3">
            Enter one rule per line. Use <code className="inline-code">→</code> or <code className="inline-code">-&gt;</code> to
            separate the left and right sides. Use <code className="inline-code">|</code> to separate alternatives.
            Symbols may be written with spaces or, for compact grammars such as <code className="inline-code">aSb</code>, without spaces.
          </p>
          <pre className="code-block text-sm">
{`S -> a S b | ε
E -> E + T | T
T -> T * F | F
F -> ( E ) | id`}
          </pre>
          <p className="mt-3 text-[15px] leading-7 text-muted-foreground">
            Non-terminals are inferred from left-hand sides. Everything else is treated as a terminal. Use <code className="inline-code">ε</code> for the empty string.
          </p>
        </Section>

        <Section title="How to Use the Generator" icon={<Lightbulb className="h-4 w-4" />}>
          <ol className="list-decimal space-y-3 pl-5">
            <li>Select an example grammar or type your own productions.</li>
            <li>Enter the string you want the grammar to generate.</li>
            <li>Choose whether you want a leftmost derivation, rightmost derivation, or both.</li>
            <li>Click <strong>Generate</strong> to compute the derivation and corresponding parse tree.</li>
            <li>Use the step controls to move through each sentential form.</li>
            <li>Switch to the <strong>Visualizer</strong> tab to study construction, ambiguity, and yield using the most recent result.</li>
          </ol>
        </Section>

        <Section title="Understanding the Parse Tree">
          <p>
            A parse tree visually represents the structure of a derivation. The <strong>root</strong> is the start symbol,
            <strong> internal nodes</strong> are non-terminals that were expanded, and <strong>leaves</strong> are terminals
            (or ε) that form the final derived string.
          </p>
          <p className="mt-3">
            Reading the leaves from left to right gives the <strong>yield</strong>. This is often the quickest way to verify
            that a derivation and a parse tree describe the same string.
          </p>
        </Section>

        <Section title="Ambiguity">
          <p>
            A grammar is <strong>ambiguous</strong> if some string has more than one distinct parse tree
            or, equivalently, more than one valid derivation order that leads to different structure.
          </p>
          <p className="mt-3">
            This tool generates one valid derivation per string in the Generator, while the Visualizer includes
            a dedicated ambiguity example so students can compare two competing tree structures side by side.
          </p>
        </Section>
      </div>
    </motion.div>
  );
}

function Section({
  title,
  children,
  icon,
}: {
  title: string;
  children: React.ReactNode;
  icon?: React.ReactNode;
}) {
  return (
    <section className="rounded-2xl border border-border bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(247,247,240,0.94))] p-7 shadow-[0_24px_54px_-40px_rgba(84,134,135,0.9)]">
      <div className="mb-3 flex items-center gap-2 text-primary">
        {icon}
        <h2 className="text-[17px] font-medium">{title}</h2>
      </div>
      <div className="text-[15px] leading-[1.9] text-foreground">{children}</div>
    </section>
  );
}
