import { motion } from 'framer-motion';

export default function HelpPage() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 6 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35 }}
    >
      <div className="bg-card rounded-2xl border border-border p-8 max-w-3xl mx-auto space-y-8">
        <Section title="What is a Context-Free Grammar?">
          <p>
            A context-free grammar (CFG) is a formal system used to describe the syntax of programming languages,
            natural language subsets, and other structured formats. It consists of production rules that define how
            strings in a language can be generated by repeatedly replacing non-terminal symbols. CFGs are central
            to compiler design and computational linguistics.
          </p>
        </Section>

        <Section title="Grammar Input Format">
          <p className="mb-3">
            Enter one rule per line. Use <code className="inline-code">→</code> or <code className="inline-code">-&gt;</code> to
            separate the left and right sides. Use <code className="inline-code">|</code> to separate alternatives.
            Separate symbols with spaces.
          </p>
          <pre className="code-block text-xs">
{`S → a S b | ε
E → E + T | T
T → T * F | F
F → ( E ) | id`}
          </pre>
          <p className="mt-3 text-muted-foreground text-xs">
            Non-terminals are inferred from left-hand sides. Everything else is treated as a terminal.
            Use <code className="inline-code">ε</code> for the empty string.
          </p>
        </Section>

        <Section title="How to Use the Generator">
          <ol className="list-decimal list-inside space-y-2">
            <li>Navigate to the <strong>Generator</strong> tab.</li>
            <li>Select a preset example or enter your own grammar rules.</li>
            <li>Type the input string you want to parse (symbols separated by spaces).</li>
            <li>Choose a derivation type: Leftmost, Rightmost, or Both.</li>
            <li>Click <strong>Generate</strong> to compute the derivation and parse tree.</li>
            <li>Use the step controls to walk through the derivation one step at a time.</li>
          </ol>
        </Section>

        <Section title="Understanding the Parse Tree">
          <p>
            A parse tree visually represents the structure of a derivation. The <strong>root</strong> is the start symbol.
            <strong> Internal nodes</strong> are non-terminals that were expanded using production rules.
            <strong> Leaves</strong> are terminal symbols (or ε) that form the final derived string.
            Reading the leaves from left to right gives you the <strong>yield</strong> — the string generated by the grammar.
          </p>
        </Section>

        <Section title="Ambiguity">
          <p>
            A grammar is <strong>ambiguous</strong> if some string has more than one distinct parse tree
            (equivalently, more than one leftmost or rightmost derivation). This tool generates one valid
            derivation per string. To explore ambiguity, visit the <strong>Visualizer</strong> tab where
            you can compare multiple parse trees for the same input.
          </p>
        </Section>
      </div>
    </motion.div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-[15px] font-medium text-primary mb-3">{title}</h2>
      <div className="text-sm text-foreground leading-[1.8]">{children}</div>
    </section>
  );
}
